---
# Alternative implementation using community.general.proxmox collection
# Note: This requires installing the collection: ansible-galaxy collection install community.general

- name: Create Proxmox resource pools (alternative method)
  community.general.proxmox:
    api_host: "{{ ansible_host }}"
    api_user: "{{ pve_api_user }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    validate_certs: no
    pool: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    state: present
  loop: "{{ pve_pools | default([]) }}"
  delegate_to: "{{ groups[pve_group][0] }}"
  run_once: true