---
# Create Proxmox resource pools using the API
- name: Create Proxmox resource pools
  uri:
    url: "https://{{ ansible_host }}:8006/api2/json/pools"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
    body_format: form-urlencoded
    body:
      poolid: "{{ item.name }}"
      comment: "{{ item.comment | default('') }}"
    validate_certs: no
    status_code: [200, 500]  # 500 might be returned if pool already exists
  loop: "{{ pve_pools | default([]) }}"
  register: pool_creation
  failed_when: 
    - pool_creation.status == 500
    - "'already exists' not in pool_creation.json.message"
  delegate_to: "{{ groups[pve_group][0] }}"
  run_once: true

- name: Add VMs to pools
  uri:
    url: "https://{{ ansible_host }}:8006/api2/json/pools/{{ item.name }}"
    method: PUT
    headers:
      Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
    body_format: form-urlencoded
    body:
      vms: "{{ item.vms | join(',') }}"
    validate_certs: no
    status_code: [200, 500]
  loop: "{{ pve_pools | default([]) }}"
  register: vm_assignment
  failed_when: 
    - vm_assignment.status == 500
    - "'already a pool member' not in vm_assignment.json.message"
  when: item.vms is defined and item.vms | length > 0
  delegate_to: "{{ groups[pve_group][0] }}"
  run_once: true

- name: Add storage to pools
  uri:
    url: "https://{{ ansible_host }}:8006/api2/json/pools/{{ item.name }}"
    method: PUT
    headers:
      Authorization: "PVEAPIToken={{ pve_api_user }}!{{ pve_api_token_id }}={{ pve_api_token_secret }}"
    body_format: form-urlencoded
    body:
      storage: "{{ item.storage | join(',') }}"
    validate_certs: no
    status_code: [200, 500]
  loop: "{{ pve_pools | default([]) }}"
  register: storage_assignment
  failed_when: 
    - storage_assignment.status == 500
    - "'already a pool member' not in storage_assignment.json.message"
  when: item.storage is defined and item.storage | length > 0
  delegate_to: "{{ groups[pve_group][0] }}"
  run_once: true