---
# defaults/main.yml for proxmox_gpu_passthrough

proxmox_gpu_passthrough_enabled: true

proxmox_gpu_passthrough_modules:
  - vfio
  - vfio_iommu_type1
  - vfio_pci
  - vfio_virqfd

proxmox_gpu_passthrough_blacklist:
  - nouveau
  - nvidia
  - nvidiafb
  - radeon
  - amdgpu

proxmox_gpu_passthrough_pci_ids: ""

proxmox_gpu_passthrough_reboot: true