---
# Simple playbook to add remaining nodes to existing cluster
- hosts: pve-1,pve-2
  become: True
  serial: 1  # Add nodes one at a time
  vars:
    ansible_command_timeout: 900  # 15 minutes
    ansible_ssh_timeout: 300     # 5 minutes
  tasks:
    - name: Check if node is already in cluster
      command: pvecm status
      register: cluster_status
      failed_when: false
      changed_when: false

    - name: Add node to Proxmox cluster
      command: pvecm add 10.0.40.10
      register: cluster_join_result
      when: cluster_status.rc != 0
      timeout: 900
      
    - name: Wait for cluster synchronization
      pause:
        seconds: 30
      when: cluster_join_result is changed
      
    - name: Verify cluster membership
      command: pvecm status
      register: final_status
      when: cluster_join_result is changed
      
    - name: Display cluster status
      debug:
        var: final_status.stdout_lines
      when: cluster_join_result is changed