---
# Configure secondary network interfaces for 10.0.70.0/24
- hosts: pve01
  become: True
  serial: 1
  tasks:
    - name: Configure /etc/network/interfaces with secondary network
      template:
        src: "{{ interfaces_template }}"
        dest: /etc/network/interfaces
        backup: yes
      register: _configure_interfaces

    - name: Restart networking if interfaces changed
      shell: "systemctl restart networking"
      when: _configure_interfaces is changed

    - name: Wait for network to stabilize
      pause:
        seconds: 10
      when: _configure_interfaces is changed

    - name: Verify secondary interface is up
      command: ip addr show
      register: ip_output
      when: _configure_interfaces is changed

    - name: Display network configuration
      debug:
        var: ip_output.stdout_lines
      when: _configure_interfaces is changed