[tasks]
default = "mise tasks ls"
list = "mise tasks ls"

setup = "doppler run --project project-proxmoxhosts -- ansible-galaxy install -r roles/requirements.yml --force"
init = "mise run setup"
plan = ".mise/tasks/run-site --check --diff"
check = ".mise/tasks/run-site --check --diff"
apply = ".mise/tasks/run-site"
"apply-verbose" = ".mise/tasks/run-site -vv"
"apply-no-ssh" = ".mise/tasks/run-site --skip-tags ssh_cluster_config"

"ceph-remove-storage-plan" = ".mise/tasks/run-playbook remove_cephfs_storage.yml --check --diff"
"ceph-remove-storage-apply" = ".mise/tasks/run-playbook remove_cephfs_storage.yml"
"network-configure-secondary" = ".mise/tasks/run-playbook configure_secondary_network.yml"
