---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    # --------------------------------------------------------------------------
    # 1. Stop Services & Kill Processes
    # --------------------------------------------------------------------------
    - name: Stop all Ceph systemd targets
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      ignore_errors: true
      loop:
        - ceph-mon.target
        - ceph-mgr.target
        - ceph-mds.target
        - ceph-osd.target

    - name: Kill all Ceph and KVM processes
      shell: "killall -9 ceph-mon ceph-mgr ceph-mds ceph-osd kvm || true"
      ignore_errors: true

    # --------------------------------------------------------------------------
    # 2. Unmount & Unmap Storage
    # --------------------------------------------------------------------------
    - name: Unmount all CephFS mounts
      shell: |
        mount -t ceph | awk '{print $3}' | xargs -r umount -f
        umount -f /mnt/pve/cephfs-vm || true
      ignore_errors: true

    - name: Unmap all RBD devices
      shell: |
        rbd unmap -a || true
        # Force remove via sysfs if standard unmap fails
        for dev in /sys/bus/rbd/devices/*; do
          if [ -e "$dev" ]; then
            echo "${dev##*/}" > /sys/bus/rbd/remove_single
          fi
        done
      ignore_errors: true

    - name: Unmount OSD paths
      shell: "mount | grep /var/lib/ceph/osd | awk '{print $3}' | xargs -r umount -f"
      ignore_errors: true

    # --------------------------------------------------------------------------
    # 3. Purge Configuration & Data
    # --------------------------------------------------------------------------
    - name: Remove Ceph configuration directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ceph
        - /var/lib/ceph
        - /var/log/ceph
        - /etc/pve/ceph.conf
        - /etc/pve/priv/ceph
        - /etc/pve/priv/ceph.client.admin.keyring
        - /etc/pve/priv/ceph.mon.keyring
        - /etc/pve/priv/ceph.mgr.keyring

    # --------------------------------------------------------------------------
    # 4. Uninstall Packages
    # --------------------------------------------------------------------------
    # We purposefully comment out package removal to avoid breaking Proxmox
    # dependencies, but we will clean up 'ceph-common' config if it remains.
    - name: Purge Ceph packages (Safe Mode - minimal)
      command: "pveceph purge"
      ignore_errors: true

    # --------------------------------------------------------------------------
    # 5. Wipe Disks
    # --------------------------------------------------------------------------
    - name: Zap NVMe disk (Partition Table)
      shell: "sgdisk --zap-all /dev/nvme0n1"
      ignore_errors: true

    - name: Wipe NVMe disk (Data - First 200MB)
      shell: "dd if=/dev/zero of=/dev/nvme0n1 bs=1M count=200 oflag=direct status=none"
      ignore_errors: true

    - name: Reload Partition Table
      command: "partprobe /dev/nvme0n1"
      ignore_errors: true

    # --------------------------------------------------------------------------
    # 6. Kernel Module Cleanup
    # --------------------------------------------------------------------------
    - name: Unload Ceph Kernel Modules
      modprobe:
        name: "{{ item }}"
        state: absent
      ignore_errors: true
      loop:
        - ceph
        - rbd
        - libceph

    # --------------------------------------------------------------------------
    # 7. Final Sanity Check
    # --------------------------------------------------------------------------
    - name: Recreate clean /etc/ceph directory
      file:
        path: /etc/ceph
        state: directory
        owner: root
        group: root
        mode: 0755
