---
- hosts: all
  become: true
  tasks:
    - name: Remove ceph storage
      command: "pvesm remove {{ item }}"
      run_once: true
      register: remove_result
      failed_when: 
        - remove_result.rc != 0 
        - "'storage does not exist' not in remove_result.stderr"
      loop:
        - cephfs-vm
        - ceph1
        - vm-storage