---

# ---------------------------------------------------------------------------- #
#                                  Preparation                                 #
# ---------------------------------------------------------------------------- #

# ---------------------------------- Set NTP --------------------------------- #
- hosts: all
  become: True
  tasks:
  - name: Configure systemd-timesyncd
    lineinfile:
      path: /etc/systemd/timesyncd.conf
      regexp: '^#?NTP='
      line: 'NTP=0.uk.pool.ntp.org 1.uk.pool.ntp.org 2.uk.pool.ntp.org 3.uk.pool.ntp.org'
      backup: yes
    notify: restart timesyncd

  - name: Set timezone
    timezone:
      name: "{{ ntp_timezone }}"

  - name: Enable and start systemd-timesyncd
    systemd:
      name: systemd-timesyncd
      enabled: yes
      state: started

  handlers:
  - name: restart timesyncd
    systemd:
      name: systemd-timesyncd
      state: restarted

# ------------------------------ Deploy SSH key ------------------------------ #
- hosts: pve01
  become: True
  tasks:
  - name: Deploy SSH public key to Proxmox server
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', playbook_dir + '/files/root_pve_rsa.pub') }}"
      comment: "Ansible automation key"

# ---------------------- Configure networking [optional] --------------------- #
- hosts: pve01
  become: True
  serial: 1
  tasks:
  - name: Install bridge-utils
    apt:
      name: bridge-utils

  - name: Configure /etc/network/interfaces
    template:
      src: "{{ interfaces_template }}"
      dest: /etc/network/interfaces
    register: _configure_interfaces

  - block:
    - name: Reboot for networking changes
      shell: "sleep 5 && shutdown -r now 'Networking changes found, rebooting'"
      async: 1
      poll: 0

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 15
    when: _configure_interfaces is changed

# ---------------------------------------------------------------------------- #
#                                Deploy Proxmox                                #
# ---------------------------------------------------------------------------- #
- hosts: pve01
  become: True
  pre_tasks:
    # Ensure hostname resolution for all cluster nodes
    - name: Add cluster hostnames to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ hostvars[item]['ansible_host'] }}\\s+{{ item }}"
        line: "{{ hostvars[item]['ansible_host'] }} {{ item }}.fabricesemti.dev {{ item }}"
        backup: yes
      loop: "{{ groups['pve01'] }}"
      when: hostvars[item]['ansible_host'] is defined
  roles:
  - lae.proxmox
  post_tasks:
    # Apply our working SSH cluster configuration
    - name: Apply custom SSH cluster configuration
      include_tasks: tasks/ssh_cluster_simple.yml
  handlers:
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted

# ---------------------------------------------------------------------------- #
#                                Post-deployment                               #
# ---------------------------------------------------------------------------- #

# ----------------------------- Configure backups ---------------------------- #
