---

# ---------------------------------------------------------------------------- #
#                                  Preparation                                 #
# ---------------------------------------------------------------------------- #

# ---------------------------------- Set NTP --------------------------------- #
- hosts: all
  become: True
  roles:
  - geerlingguy.ntp

# ------------------------------ Deploy SSH key ------------------------------ #
- hosts: pve01
  become: True
  tasks:
  - name: Deploy SSH public key to Proxmox server
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', playbook_dir + '/files/root_pve_rsa.pub') }}"
      comment: "Ansible automation key"

# ---------------------- Configure networking [optional] --------------------- #
- hosts: pve01
  become: True
  serial: 1
  tasks:
  - name: Install bridge-utils
    apt:
      name: bridge-utils

  - name: Configure /etc/network/interfaces
    template:
      src: "{{ interfaces_template }}"
      dest: /etc/network/interfaces
    register: _configure_interfaces

  - block:
    - name: Reboot for networking changes
      shell: "sleep 5 && shutdown -r now 'Networking changes found, rebooting'"
      async: 1
      poll: 0

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 15
    when: _configure_interfaces is changed

# ---------------------------------------------------------------------------- #
#                                Deploy Proxmox                                #
# ---------------------------------------------------------------------------- #
- hosts: pve01
  become: True
  roles:
  - lae.proxmox

# ---------------------------------------------------------------------------- #
#                                Post-deployment                               #
# ---------------------------------------------------------------------------- #

# ----------------------------- Configure backups ---------------------------- #
