---
# Proxmox Backup Configuration defaults

# Backup storage location (must exist in Proxmox)
backup_storage: "nfs-proxmox-backup"

# VM Backup Configuration
vm_backup:
  name: "vm-backup"
  schedule: "01:00" # 1:00 AM (24-hour format)
  dow: "sun" # Day of week: sun, mon, tue, wed, thu, fri, sat
  vm_ids: [1020, 1021] # List of VM IDs to backup
  enabled: true
  compress: "zstd" # Compression: none, lzo, gzip, zstd
  mode: "snapshot" # Backup mode: snapshot, suspend, stop
  retention:
    keep_daily: 7 # Keep daily backups for 7 days
    keep_weekly: 4 # Keep weekly backups for 4 weeks
    keep_monthly: 3 # Keep monthly backups for 3 months
  notification: true # Send notifications on backup completion
  email_on_failure: false # Send email notifications always (not just on failure)

# Template Backup Configuration
template_backup:
  name: "template-backup"
  schedule: "02:00" # 2:00 AM (24-hour format)
  dow: "sun" # Day of week: sun, mon, tue, wed, thu, fri, sat
  vm_ids: [6006] # List of template IDs to backup
  enabled: true
  compress: "zstd"
  mode: "snapshot"
  retention:
    keep_daily: 3 # Templates change less frequently
    keep_weekly: 2
    keep_monthly: 6 # Keep more monthly backups for templates
  notification: true
  email_on_failure: false

# Global backup settings
backup_global:
  # Backup window settings
  max_workers: 1 # Number of parallel backup jobs
  bandwidth_limit: 0 # Bandwidth limit in KB/s (0 = unlimited)

  # Notification settings
  notification_target: "mail-to-root" # Notification target (configured separately)

  # Performance settings
  ionice: 7 # I/O priority (0-7, 7 = lowest priority)
  lockwait: 180 # Maximum time to wait for VM lock (minutes)
