---
proxmox_ceph_maintenance_script: /usr/local/sbin/proxmox-ceph-maintenance
proxmox_ceph_maintenance_log: /var/log/proxmox-ceph-maintenance.log
proxmox_ceph_maintenance_cron_name: Weekly Proxmox Ceph maintenance
proxmox_ceph_maintenance_weekday: "0"
proxmox_ceph_maintenance_hour: "7"
proxmox_ceph_maintenance_minute: "0"
