---
# Gmail SMTP Configuration defaults
gmail_smtp_server: smtp.gmail.com
gmail_smtp_port: 587
gmail_smtp_username: ""  # Set in inventory or group_vars
gmail_smtp_password: ""  # Set in inventory or group_vars (use app password)
gmail_smtp_from_address: "{{ gmail_smtp_username }}"
gmail_smtp_from_name: "Proxmox Cluster"

# Proxmox notification settings
proxmox_notification_enabled: true
proxmox_notification_test: false  # Set to true to send test email after configuration