---
- name: postmap sasl_passwd
  command: postmap /etc/postfix/sasl_passwd

- name: postmap generic
  command: postmap /etc/postfix/generic

- name: restart postfix
  systemd:
    name: postfix
    state: restarted