---
- name: Ensure required environment variables are set
  assert:
    that:
      - gmail_smtp_username is defined and gmail_smtp_username != ""
      - gmail_smtp_password is defined and gmail_smtp_password != ""
    fail_msg: |
      Gmail SMTP credentials must be defined via environment variables.
      
      Please create .envrc file with:
        export GMAIL_SMTP_USERNAME="your-email@gmail.com"
        export GMAIL_SMTP_PASSWORD="your-app-password"
      
      Then run: direnv allow
      
      See .envrc.example for template.

- name: Install required packages for SMTP
  apt:
    name:
      - libsasl2-modules
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Configure Postfix main.cf for Gmail SMTP relay
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    backup: yes
    mode: '0644'
  notify: restart postfix

- name: Create SASL password file
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: '0600'
    owner: root
    group: root
  notify:
    - postmap sasl_passwd
    - restart postfix

- name: Configure Postfix generic mapping
  template:
    src: generic.j2
    dest: /etc/postfix/generic
    mode: '0644'
  notify:
    - postmap generic
    - restart postfix

- name: Start and enable Postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: Send test email if requested
  mail:
    to: "{{ gmail_smtp_username }}"
    subject: "Proxmox {{ inventory_hostname }} - SMTP Configuration Test"
    body: |
      This is a test email from Proxmox node {{ inventory_hostname }}.
      
      Gmail SMTP configuration has been successfully applied.
      
      Timestamp: {{ ansible_date_time.iso8601 }}
      Node: {{ inventory_hostname }}
      IP: {{ ansible_default_ipv4.address }}
  when: proxmox_notification_test | default(false) | bool