---
proxmox_vm_ip: "10.0.30.60"
proxmox_vm_cidr: 24
proxmox_vm_gateway: "{{ proxmox_vm_ip | regex_replace('\\.[0-9]+$', '.1') }}"
proxmox_vm_vmid: "{{ (proxmox_vm_ip.split('.')[2] | int * 100) + (proxmox_vm_ip.split('.')[3] | int) }}"
proxmox_vm_vlan: "{{ proxmox_vm_ip.split('.')[2] | int }}"
proxmox_vm_bridge: vmbr0
proxmox_vm_name: ansible-test-01
proxmox_vm_memory: 3072
proxmox_vm_sockets: 2
proxmox_vm_cores: 2
proxmox_vm_reboot_on_change: true
proxmox_vm_template_vmid: 9007
proxmox_vm_template_node: pve-2
proxmox_vm_template_host: pve-2.fabricesemti.dev
proxmox_vm_target_node: pve-0
proxmox_vm_full_clone: true
proxmox_vm_started: true
proxmox_vm_state: present
proxmox_vm_destroy_purge: true
